name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: GORACE="halt_on_error=1" go test --race -v -coverprofile=profile.cov ./...

    - name: Update coverage report
      uses: shogo82148/actions-goveralls@v1.4.2
      with:
        path-to-profile: profile.cov
